<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM2igHfU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM2igHfU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM2igHfU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM2igHfU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM2igHfU\App_KernelDevDebugContainer([
    'container.build_hash' => 'M2igHfU',
    'container.build_id' => '6fadb3f1',
    'container.build_time' => 1681761130,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM2igHfU');
