<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUvflpP8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUvflpP8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUvflpP8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUvflpP8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUvflpP8\App_KernelDevDebugContainer([
    'container.build_hash' => 'UvflpP8',
    'container.build_id' => 'c26a1aba',
    'container.build_time' => 1678265862,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUvflpP8');
