<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIF0YZci\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIF0YZci/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIF0YZci.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIF0YZci\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIF0YZci\App_KernelDevDebugContainer([
    'container.build_hash' => 'IF0YZci',
    'container.build_id' => 'ca93ac5f',
    'container.build_time' => 1681763021,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIF0YZci');
