<?php

namespace ContainerF4yJFeN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XvT4AnJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XvT4AnJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XvT4AnJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'motPartieRepository' => ['privates', 'App\\Repository\\MotPartieRepository', 'getMotPartieRepositoryService', true],
            'motRepository' => ['privates', 'App\\Repository\\MotRepository', 'getMotRepositoryService', true],
            'partieRepository' => ['privates', 'App\\Repository\\PartieRepository', 'getPartieRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'motPartieRepository' => 'App\\Repository\\MotPartieRepository',
            'motRepository' => 'App\\Repository\\MotRepository',
            'partieRepository' => 'App\\Repository\\PartieRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
