<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Partie extends \App\Entity\Partie implements \Doctrine\Persistence\Proxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateDebut' => [parent::class, 'dateDebut', null],
        "\0".parent::class."\0".'etat' => [parent::class, 'etat', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'joueur1' => [parent::class, 'joueur1', null],
        "\0".parent::class."\0".'joueur2' => [parent::class, 'joueur2', null],
        "\0".parent::class."\0".'motParties' => [parent::class, 'motParties', null],
        "\0".parent::class."\0".'resultat' => [parent::class, 'resultat', null],
        "\0".parent::class."\0".'tour' => [parent::class, 'tour', null],
        'dateDebut' => [parent::class, 'dateDebut', null],
        'etat' => [parent::class, 'etat', null],
        'id' => [parent::class, 'id', null],
        'joueur1' => [parent::class, 'joueur1', null],
        'joueur2' => [parent::class, 'joueur2', null],
        'motParties' => [parent::class, 'motParties', null],
        'resultat' => [parent::class, 'resultat', null],
        'tour' => [parent::class, 'tour', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
