<?php

namespace ContainerC3LIzgX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W6G82BPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w6G82BP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w6G82BP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'partieRepository' => ['privates', 'App\\Repository\\PartieRepository', 'getPartieRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'partieRepository' => 'App\\Repository\\PartieRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
